### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by grlee77**
update to get a python 3.6 build

### CODE REVIEW

**Comment by lsorber** [comment]
Hi @grlee77, next to Python 3.6 support, could you also bump to the latest minor version (released a few days ago)? Thanks!

**Comment by grlee77** [comment]
Thanks for the reminder @lsorber.  Assuming it passes CI this time around this will be merged soon.

**Comment by isuruf** [comment]
You can also try, [`noarch: python`](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/meta.rst#building-noarch-packages)?

**Comment by grlee77** [comment]
Thanks @isuruf!  now using `noarch: python`

**Pull request merged**
